### ISSUE TITLE
Input fails at the first 'recall' module

### ISSUE THREAD

**Issue by QunjunLIANG** [neuropsychology/ComplexSpan#2]
Hi, thanks for providing such a wonderful tool. 

I ran the .psyexp file through Psychopy v3.0.6, on Windows 10. 

Everything went well at the very beginning, until I found myself seemed be stuck in the first 'recall' module.

I can't input any characters through my keyboard, excluding the 'escape' to quit the experiment.

The picture shows the frame of screenshot that I am stuck in. Any ideas to overcome this problem?  Should I update my Psychopy version? Thanks.
![123](https://user-images.githubusercontent.com/33589477/87848835-46a67900-c916-11ea-810d-04e5d45d3eed.png)

**Comment by zen-juen** [comment]
Hi @QunJunLIANG! Thanks for opening your first issue with us!

I'm assuming the task.psyexp file that you ran is the raw file you downloaded from this repo without having modified anything. That is indeed odd - with regards to this screenshot, did "SPACE" appear when you enter the spacebar? (the raw file does not allow any instances of spacebar entries)

**Comment by QunjunLIANG** [comment]
Hi @zen-juen , thanks for your timely reply.

Yes, I did not modify the task.psyexp file. The "SPACE" shows up immediately when the code ran into the 'recall' module. I did nothing when the "SPACE" emerge on the screen, and the code seemed non-response to the keyboard inputs like 'enter' or 'backspace'. However, 'escape' could still work to quit the program. 

Maybe something wrong with key_resp_6 ? Or maybe the 'SPACE' gotten in key_resp_5 disturbs the input in key_resp_6 ? Should I add a command to clean the input in key_resp_5 before key_resp_6 ?

**Comment by zen-juen** [comment]
@QunjunLIANG 

The input keys (all alphabets, 'enter', 'backspace') for the first recall module is key_resp_5 and key_resp_6 (where *only* space is allowed) is engaged only in the instructions for the complex span portion - since they're quite far apart, it's unlikely that their keys are mixed up. 🤔 The space key is only allowed during instructions portions when participants press 'space' to move on, and even when space is pressed, it should not be shown on the screen at all.

![Capture](https://user-images.githubusercontent.com/54053748/87866144-9f2a5480-c9b0-11ea-9293-b4a0523badbe.PNG)

Could you upgrade your psychopy to the [latest 3.2.4 version](https://www.psychopy.org/changelog.html#psychopy-3-2-4) and then check again that your key_resp_5 corresponds to this screenshot here?

**Comment by QunjunLIANG** [comment]
Hi @zen-juen , I am happy to tell you that the bug disappeared after I updated the Psychopy version.

Thanks for your help!

**Comment by zen-juen** [comment]
@QunjunLIANG That's great! 😄 We hope this task continues to serve you well and feel free to raise more questions on this repo if you encounter any more problems!
